### ISSUE TITLE
APNS Token AND Firebase Messenging token for iOS

### ISSUE THREAD

**Issue by fvisticot** [sh-ogawa/device_token_interceptor#1]
- I need the Firebase Messaging to be able to send Push Notification from Firebase Messaging
- I need the APNS token to be used with another Push Provider (AWS)

If I use this plugin, i receive both APNS token and Firebase Messaging -> it is GOOD

BUT:
- If i try to send a push token from Firebase Messaging console with the token (firebase token) it does not work

Question:
- it this use case possible with this plugin ?
- do we need to do another ios delegate configuration to make it works ?
By example to call the FirebaseMessenging didRegisterForRemoteNotificationsWithDeviceToken to be able to complete initialisation ?

**Comment by sh-ogawa** [comment]
Hi @fvisticot
thank you for feedback.

I made this plugin to send APNs from other than FCM (eg Amazon SNS).
So it doesn't apply to the use case when you want to send APNs from FCM.
If you want to send APNs from FCM, you should not use this plugin and use firebase_messaging plugin as it is.

Can I also use APNs from both FCM and Amazon SNS, for example? About
It's a form that intercepts Delegate, so I think it's possible if you pardon this well, but I'm not an iOS engineer, so I do not know how to do it.
